import { Type } from "@sinclair/typebox";
import { get, post, patch, del } from "../../client";

function json(data: unknown) {
  return { content: [{ type: "text" as const, text: JSON.stringify(data, null, 2) }] };
}

export function register(api: any) {
  api.registerTool({ name: "clickup_teams_list", description: "List ClickUp teams/workspaces.", parameters: Type.Object({ agent_id: Type.String({ description: "Agent with ClickUp integration" }) }), async execute(_id: string, p: any) { return json(await post("/integrations/clickup/teams/list", p)); } });
  api.registerTool({ name: "clickup_spaces_list", description: "List spaces in a ClickUp team.", parameters: Type.Object({ agent_id: Type.String({ description: "Agent with ClickUp integration" }), team_id: Type.String({ description: "Team ID" }) }), async execute(_id: string, p: any) { return json(await post("/integrations/clickup/spaces/list", p)); } });
  api.registerTool({ name: "clickup_folders_list", description: "List folders in a ClickUp space.", parameters: Type.Object({ agent_id: Type.String({ description: "Agent with ClickUp integration" }), space_id: Type.String({ description: "Space ID" }) }), async execute(_id: string, p: any) { return json(await post("/integrations/clickup/folders/list", p)); } });
  api.registerTool({ name: "clickup_lists_list", description: "List lists in a ClickUp folder.", parameters: Type.Object({ agent_id: Type.String({ description: "Agent with ClickUp integration" }), folder_id: Type.String({ description: "Folder ID" }) }), async execute(_id: string, p: any) { return json(await post("/integrations/clickup/lists/list", p)); } });
  api.registerTool({ name: "clickup_tasks_list", description: "List tasks in a ClickUp list.", parameters: Type.Object({ agent_id: Type.String({ description: "Agent with ClickUp integration" }), list_id: Type.String({ description: "List ID" }) }), async execute(_id: string, p: any) { return json(await post("/integrations/clickup/tasks/list", p)); } });
  api.registerTool({ name: "clickup_task_get", description: "Get a ClickUp task.", parameters: Type.Object({ agent_id: Type.String({ description: "Agent with ClickUp integration" }), task_id: Type.String({ description: "Task ID" }) }), async execute(_id: string, p: any) { return json(await get(`/integrations/clickup/tasks/${encodeURIComponent(p.task_id)}`, { agent_id: p.agent_id })); } });
  api.registerTool({ name: "clickup_task_create", description: "Create a ClickUp task.", parameters: Type.Object({ agent_id: Type.String({ description: "Agent with ClickUp integration" }), list_id: Type.String({ description: "List ID" }), name: Type.String({ description: "Task name" }), description: Type.Optional(Type.String({ description: "Task description" })), priority: Type.Optional(Type.Integer({ description: "1=urgent 2=high 3=normal 4=low" })), status: Type.Optional(Type.String({ description: "Status name" })) }), async execute(_id: string, p: any) { return json(await post("/integrations/clickup/tasks/create", p)); } });
  api.registerTool({ name: "clickup_task_update", description: "Update a ClickUp task.", parameters: Type.Object({ agent_id: Type.String({ description: "Agent with ClickUp integration" }), task_id: Type.String({ description: "Task ID" }), name: Type.Optional(Type.String({ description: "Updated name" })), description: Type.Optional(Type.String({ description: "Updated description" })), priority: Type.Optional(Type.Integer({ description: "Updated priority" })), status: Type.Optional(Type.String({ description: "Updated status" })) }), async execute(_id: string, p: any) { const { task_id, ...body } = p; return json(await patch(`/integrations/clickup/tasks/${encodeURIComponent(task_id)}`, body)); } });
  api.registerTool({ name: "clickup_task_delete", description: "Delete a ClickUp task.", parameters: Type.Object({ agent_id: Type.String({ description: "Agent with ClickUp integration" }), task_id: Type.String({ description: "Task ID" }) }), async execute(_id: string, p: any) { return json(await del(`/integrations/clickup/tasks/${encodeURIComponent(p.task_id)}`, { agent_id: p.agent_id })); } });
  api.registerTool({ name: "clickup_comment_create", description: "Add a comment to a ClickUp task.", parameters: Type.Object({ agent_id: Type.String({ description: "Agent with ClickUp integration" }), task_id: Type.String({ description: "Task ID" }), comment_text: Type.String({ description: "Comment text" }) }), async execute(_id: string, p: any) { return json(await post("/integrations/clickup/comments/create", p)); } });
}
